[package]
authors = ["Ceri Storey <cez@necrofish.org.uk>"]
name = "antimirov"
version = "0.1.0"

[dependencies]
bit-set = "0.4.0"
dot = "0.1.2"
maplit = "0.1.3"
vec_map = "0.6.0"

[dev-dependencies]
regex = "0.1.69"

[profile]

[profile.bench]
debug = true

[profile.release]
debug = true
